### ISSUE TITLE
feat: implement a function updateRegisters and call it in inside runInstruction

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#10]
Right now there are functions to [update each register](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L175). Create a function that updates all three registers based on an instruction, and make it callable inside `runInstruction` [function](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L104).

**Comment by oxlime** [comment]
I can take this one
