### ISSUE TITLE
feat(vm): complete the implementation of `runInstruction`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#102]
At the moment, the implementation of the `runInstruction` method in the `CairoVM` structure is incomplete and needs to be completed and tested to work correctly:

https://github.com/keep-starknet-strange/cairo-zig/blob/6f683b4c98c75b5cf4ce36292f12ac3457619968/src/vm/core.zig#L138-L155

- Rust [reference implementation](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_core.rs#L391-L432)
- Python [reference implementation](https://github.com/starkware-libs/cairo-lang/blob/9e6e0e96d208608d98635ccfad5b26285c4936e1/src/starkware/cairo/lang/vm/vm_core.py#L410-L433)

**Comment by oxlime** [comment]
will take
