### ISSUE TITLE
feat: add `MemoryCell` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#109]
At the moment, in the `Memory` structure, the `data` field is a vector composed of elements of type `MaybeRelocatable`. 

https://github.com/keep-starknet-strange/cairo-zig/blob/747dc4a492d0f35e4894edb026f6273c7805d0a7/src/vm/memory/memory.zig#L31-L36

In the future, it may be desirable to add other information in addition to only a `MaybeRelocatable` type. In particular, I find the boolean flag `is_accessed` introduced by the Rust implementation quite useful in this context. I therefore propose the implementation of a `MemoryCell` structure which will initially contain the fields:
- `maybeRelocatable` of type `MaybeRelocatable`
- `isAccessed` of type boolean

This structure can then be extended and improved. In this same issue, it will also be necessary to replace the `MaybeRelocatable` type in the `data` vector of the `Memory` structure by the `MemoryCell` structure thus created.

Here are the Rust implementation details [here](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_memory/memory.rs#L19-L42).

**Comment by Deecellar** [comment]
Oh, seems interesting, I will take this feat

**Comment by lana-shanghai** [comment]
> Oh, seems interesting, I will take this feat

Assigned!

**Comment by lana-shanghai** [comment]
Hey @Deecellar could you give @oxlime a timeline when do you think this would be completed? His `runInstruction` PR is blocked by it

**Comment by oxlime** [comment]
@lana-shanghai I can take this if @Deecellar isn't working on it anymore. Should be lots of new issues want to get pr through for fib program deadline.

**Comment by oxlime** [comment]
have this almost finished I'm getting some errors in my Memory.markAsAccessed function that I think could be because of passing my value and not reference? Should i open a pr or can you check my local branch.  https://github.com/oxlime/cairo-zig/tree/feat/add_MemoryCell

Changes to Memory requires a lot of testing changes so just want to make sure this is the right direction.
