### ISSUE TITLE
feat: when running the VM pass it a json file path

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#11]
See CLI [options](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/cmd/cmd.zig#L22)

 `./zig-out/bin/cairo-zig execute --proof-mode=false` needs to look like `./zig-out/bin/cairo-zig execute --program my_cairo_program.json --proof-mode=false`

**Comment by ptisserand** [comment]
Can I take this one ?

What is the expected format for `my_cairo_program.json': CASM JSON file ?

**Comment by lana-shanghai** [comment]
Yes please do! 

Yes, the instructions are supposed to be read from `bytecode` in the program. For now let's just load the file and read the first instruction. For an initial test instruction we can take the one from decoding tests, or compile a super trivial cairo program. In the future we will need to understand if the first value is indeed a valid instruction or something else, I believe it's not always a valid instruction

**Comment by ptisserand** [comment]
Hi @lana-shanghai I will be away for 2 weeks: if you think this is blocking please unassign me.

**Comment by jobez** [comment]
i can work on this
