### ISSUE TITLE
feat: add `AddressSet` structure for memory

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#116]
At the moment, our validated addresses inside the `Memory` structure are contained inside a HashMap:

https://github.com/keep-starknet-strange/cairo-zig/blob/d677ee6aa56883d9ea6a26556be4e01a3404fa8e/src/vm/memory/memory.zig#L41-L46

To enhance this implementation, it could be better to wrap this inside a dedicated `AddressSet` data structure with dedicated methods as it is done in the Rust implementation [here](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_memory/memory.rs#L44-L82). This will extend the specific functionality and properties of this data structure.

**Comment by ndcroos** [comment]
I am interested in this. Can you assign it to me?

**Comment by tcoratger** [comment]
@ndcroos Done

**Comment by ndcroos** [comment]
I've looked into this, but I found this to be a bit above my beginner Zig level at the moment. 
If it can be a help to someone else, I've got this as a quite literal imitation of the Rust code. I use a ArrayList(u8) as the underlying structure (cairo-rs uses Vec<bv::BitVec> there).
```rust
pub const AddressSet = struct {
    const Self = @This();

    vec: std.ArrayList(u8),

    pub fn init(allocator: Allocator) Self {
        return Self { .vec = std.ArrayList(u8).init(allocator) };
    }

    pub fn deinit(self: Self) void {
        self.vec.deinit();
    }

    pub fn contains(self: *Self, addr: Relocatable) bool {
        const segment = addr.segment_index;
        if (segment < 0) {
            return false;
        }

        const segmentIndex: usize = @intCast(segment);
        const maybeSegment = self.vec.get(segmentIndex);
        const maybeBit = maybeSegment.?.get(addr.offset);
        return maybeBit.? == true;
    }

    pub fn extend(self: *Self, addresses: []Relocatable) void {
        var segment: usize = 0;
        var offset: usize = 0;
        var newBitVec: std.ArrayList(u8) = undefined;
        for (addresses) |addr| {
            segment = @intCast(addr.segment_index);
            if (addr.segment_index < 0) {
                continue;
            }
            if (segment >= self.vec.len) {
                self.vec.resize(segment + 1, newBitVec);
            }

            offset = @intCast(addr.offset);
            if (offset >= self.vec[segment].len) {
                self.vec[segment].resize(offset + 1, false);
            }
            _ = self.vec[segment].replace(offset, true);
        }
    }
};
```
But I am not sure which allocator I should choose, when invoking the init.

**Comment by ndcroos** [comment]
For me, you can take it.

**Comment by oxlime** [comment]
@ndcroos Are you in the telegram? I am new to zig also. Think a lot of people have done not much more than ziglings.

**Comment by oxlime** [comment]
@ndcroos if your making progress perhaps continue, I'm not sure this one is time sensitive... They are good at helping with pr's as they know most are new to zig. I was indicating its blocking so as to free myself take another issue. Telegram is open to help as well.    :)
