### ISSUE TITLE
refactor: replace Op0 tuple results by `Op0Result` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#121]
At the moment our Op0 operation results are handled inside a tuple which can be complex to read/handle/use:

https://github.com/keep-starknet-strange/cairo-zig/blob/0904c68e37c292c95131066f0102816e4a063767/src/vm/core.zig#L239

A dedicated `Op0Result` structure is available for that:

https://github.com/keep-starknet-strange/cairo-zig/blob/0904c68e37c292c95131066f0102816e4a063767/src/vm/core.zig#L626-L629

Then all our Op0 operation results must use this `Op0Result` structure properly.

**Comment by lana-shanghai** [comment]
Same goes for the `Op1Result`
