### ISSUE TITLE
feat: complete `set` function of the `Memory` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#124]
At the moment the implementation of the `set` function inside the `Memory` structure is not complete:

https://github.com/keep-starknet-strange/cairo-zig/blob/f7065762676d169052e9e19b3049569107ec2428/src/vm/memory/memory.zig#L98-L125

There is a lack of checks and verifications to ensure, for example, that the added element is inserted next to the last one on the segment or that another element already exists at this address to possibly return an error.

Here are the implementations that can guide our Zig implementation:
- Implementation in Rust: https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_memory/memory.rs#L119-L165
- Python implementation: https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_dict.py#L189

**Comment by oxlime** [comment]
Can take this one

**Comment by tcoratger** [comment]
> Can take this one

@oxlime Assigned

**Comment by oxlime** [comment]
I believe this should be closed with the new Data and temp Data Set function

**Comment by tcoratger** [comment]
@oxlime I think we still need to add certain checks inside with certain error returns, right? For now I just simply add the element in data without any check. I see for example, among other things, the check to know if an element already exists in the designated location, in which case it is necessary to return an error because we do not have the right to rewrite over an element (read only): https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_memory/memory.rs#L155

What do you think?

**Comment by oxlime** [comment]
i see agreed, will do
