### ISSUE TITLE
refactor: remove useless getter and setter functions

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#125]
In our structures declared as public, the fields are public and therefore accessible from outside by default as described here:https://github.com/ziglang/zig/issues/9909. 

Also, as can be seen on reference repos such as the standard library, https://github.com/tigerbeetle/tigerbeetle or https://github.com/oven-sh/bun/tree/main, the culture of getters and setters is largely not present in the Zig community.

So, there are a lot of getter and setter functions that are useful in Rust because the fields are private which can be removed from our Zig implementation because useless. 

Example of this:

https://github.com/keep-starknet-strange/cairo-zig/blob/0e61d828f16337fa4ee925aa7702806054cf03ab/src/vm/core.zig#L410-L429

**Comment by 0xicosahedron** [comment]
can i try this one?

**Comment by tcoratger** [comment]
> can i try this one?

@0xicosahedron Yes sure just assigned
