### ISSUE TITLE
feat: add comparison utils in `Relocatable` and `MaybeRelocatable`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#126]
Currently we have some basic equality, addition and subtraction operations in the `Relocatable` structure and in the `MaybeRelocatable` union enum. However, for each of these two data structures we are missing the following comparison tools:
- Less than (between two `Relocatable` and then between two `MaybeRelocatable`)
- Less or equal than (between two `Relocatable` and then between two `MaybeRelocatable`)
- Greater than (between two `Relocatable` and then between two `MaybeRelocatable`)
- Greater or equal than (between two `Relocatable` and then between two `MaybeRelocatable`)

**Reference - Python implementation:** https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/relocatable.py#L46C5-L46C5

**Comment by 0xicosahedron** [comment]
i can take this one!

**Comment by tcoratger** [comment]
> i can take this one!

@0xicosahedron Perfect just assigned
