### ISSUE TITLE
feat: add `allow_tmp_segments` flag in `computeEffectiveSizes`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#130]
The `computeEffectiveSize` function currently lacks a parameter to control the inclusion of temporary segments in the computation of effective sizes:

https://github.com/keep-starknet-strange/cairo-zig/blob/9af9d13cd5231fead222a23efe09fafa1a9c1d4f/src/vm/memory/segments.zig#L169-L180

This enhancement proposes the addition of a `allow_tmp_segments` boolean flag to the function's signature, enabling users to decide whether temporary segments should be considered.

**Enhancement Proposal:**
```
pub fn computeEffectiveSize(self: *Self, allow_tmp_segments: bool) !std.AutoArrayHashMap(u32, u32) {
    // Implementation with the new allow_tmp_segments flag.
    // ...
    // ...
}
```

**Additional Context:**
The addition of the `allow_tmp_segments` flag offers users more control over the computation of effective sizes, aligning the Zig implementation with the Python counterpart.

```
// Example Usage
const allowTmpSegments: bool = true; // Set to true to include temporary segments
const effectiveSizes = myCairoVM.computeEffectiveSize(allowTmpSegments);
```

**Reference Python implementation:** 
https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_segments.py#L75-L96

**Comment by lambda-0x** [comment]
i can take this

**Comment by tcoratger** [comment]
> i can take this

@lambda-0x Sure just assigned

**Comment by lambda-0x** [comment]
it seems that `key` in `segment_used_size` can be a negative number:

https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_segments.py#L85-L88

but for us the key is `u32` so it cannot store negative value, should i change it to be `i32`?

**Comment by tcoratger** [comment]
> it seems that `key` in `segment_used_size` can be a negative number:
> 
> https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_segments.py#L85-L88
> 
> but for us the key is `u32` so it cannot store negative value, should i change it to be `i64` to not reduce the current range?
> 
> https://github.com/keep-starknet-strange/cairo-zig/blob/9af9d13cd5231fead222a23efe09fafa1a9c1d4f/src/vm/memory/segments.zig#L28-L33

@lambda-0x Yes I think so because you will need negative indexes in order to store temporary segments here. `i32` should be enough no?

**Comment by lambda-0x** [comment]
@tcoratger then when we assign `self.n_temp_segments` (which is u32, since count being negative doesn't make sense) to `first_segment_index` (which would be i32) we would need to make sure it doesn't overflow.

https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_segments.py#L85

**Comment by lambda-0x** [comment]
went with `i64` for now so it doesn't reduce the effective range of other variables
