### ISSUE TITLE
tests: add `Instruction` instance test util variable

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#136]
## Overview

Currently, the `Instruction` structure is extensively used in various unit tests, such as in:

https://github.com/keep-starknet-strange/cairo-zig/blob/194de20850dcab37541385c7cce5d7773da67535/src/vm/core_test.zig#L1468-L1480

The current approach involves redeclaring a new instance of the `Instruction` structure for each test, resulting in cumbersome and verbose code.

## Proposed Enhancement

To improve the clarity and maintainability of the code, I recommend a different approach. Instead of frequently invoking the `Instruction.default()` function, which may lead to huge computational work (calling `decode` function each time) and potential issues if the function fails, I propose introducing a utility test variable. This variable will store a default structure, enabling easy reuse and modification across all unit tests.

## Benefits

1. **Readability**: The proposed approach streamlines the code, making it more readable by reducing redundancy.
2. **Maintainability**: A centralized test variable facilitates easy modifications across tests, enhancing maintainability.
3. **Error Isolation**: In the event of an issue with `Instruction.default()`, this approach isolates the problem to the utility variable, making troubleshooting more straightforward.

## Example Implementation

```zig
const utilTestInstruction: Instruction = Instruction.default();

// Example usage in a unit test
test "Some test case" {
    // Modify utilTestInstruction as needed for this specific test
    utilTestInstruction.someField = someValue;

    // Rest of the test logic
    // ...
}

**Comment by dhruvkelawala** [comment]
I can take this one :)

**Comment by tcoratger** [comment]
> I can take this one :)

Assigned
