### ISSUE TITLE
doc: adding Documentation for Cairo Error Types

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#137]
## Description

The current codebase defines several error types within Cairo, but lacks comprehensive documentation for these error types. Adding detailed documentation for each error type will improve the clarity and understanding of potential issues within the codebase.

https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/error.zig

## Requested Enhancement

Enhance the codebase by providing comprehensive documentation for each major error type, and include detailed documentation for each specific error within every error type.

## Expected Outcome

Developers and contributors will have a clearer understanding of potential errors, leading to more effective debugging and maintenance.

**Comment by ndcroos** [comment]
Hi, I'd like to work on this.

**Comment by tcoratger** [comment]
> Hi, I'd like to work on this.

@ndcroos Assigned
