### ISSUE TITLE
feat: add validation rules in `Memory` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#141]
Currently, there are two essential utility functions absent in the `Memory` structure that play a crucial role in validating memory. We need the following implementations in Ziglang:

### A `validateMemoryCell` method
- Purpose: To validate a specific memory cell.
- Link to Rust Implementation: [`validate_memory_cell`](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_memory/memory.rs#L315-L327)

### A `validateExistingMemory` method
- Purpose: To validate the entire current memory based on predefined validation rules.
- Link to Rust Implementation: [`validate_existing_memory`](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_memory/memory.rs#L330-L347)

**Comment by oxlime** [comment]
can take this one

**Comment by tcoratger** [comment]
> can take this one

@oxlime Perfect, just assigned

**Comment by oxlime** [comment]
This is blocked by #116 after looking into it further.
