### ISSUE TITLE
refactor: simplify `MaybeRelocatable` instance declarations in unit tests

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#144]
At the moment, everywhere in the code, we have places where `MaybeRelocatable` instances are declared in a quite verbose way:
- For `Felt252`:
https://github.com/keep-starknet-strange/cairo-zig/blob/827b37b6682f9151cf81ab5f88ed2bc79db09511/src/vm/core_test.zig#L82

This should be replaced by a call to the purpose built util:
```zig
fromU256(8),
```

- For `Relocatable`:
https://github.com/keep-starknet-strange/cairo-zig/blob/827b37b6682f9151cf81ab5f88ed2bc79db09511/src/vm/core_test.zig#L1343

This should be replaced by a call to the purpose built util:
```zig
fromSegment(0, 1),
```

**Comment by pjserol** [comment]
I can take this one?

**Comment by tcoratger** [comment]
> I can take this one?

@pjserol Just assigned
