### ISSUE TITLE
feat: add `add` and `sub` utils in `MaybeRelocatable` union

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#158]
At the moment, we don't have any util to add and subtract two `MaybeRelocatable` together. We need to implement this in the `MaybeRelocatable` structure:
- The `add` method performs addition between two MaybeRelocatable values. It checks the type of the operands and performs addition based on the types. Reference for the `add` implementation: https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/types/relocatable.rs#L235-L251
- The `sub` method, on the other hand, handles subtraction operations. Similar to `add`, it checks the types of the operands and performs subtraction accordingly. Reference for the `sub` implementation: https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/types/relocatable.rs#L253-L286

For Zig, we would need to replicate this logic, ensuring proper handling of different types of `MaybeRelocatable` values during addition and subtraction. Zig syntax and type system will differ from Rust, so you'll need to adapt this logic accordingly while maintaining the same behavior and rules for handling these types of operations.

**Comment by coratgerl** [comment]
I can take it

**Comment by tcoratger** [comment]
> I can take it

Assigned
