### ISSUE TITLE
refactor: better labels for errors in `Relocatable` and `MaybeRelocatable`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#161]
At the moment, in both the `Relocatable` and `MaybeRelocatable` structures, we have errors that are not labeled properly using our error types that can be found in the `error.zig` file.
- Example in `Relocatable` structure: https://github.com/keep-starknet-strange/cairo-zig/blob/d50e5492e15d454f7882703df4824866543aa5a2/src/vm/memory/relocatable.zig#L114
- Example in `MaybeRelocatable` union: https://github.com/keep-starknet-strange/cairo-zig/blob/d50e5492e15d454f7882703df4824866543aa5a2/src/vm/memory/relocatable.zig#L391

We need to label these errors properly in order to be able to group them and enforce a better typing.

**Comment by dhruvkelawala** [comment]
I can take this one up

**Comment by tcoratger** [comment]
> I can take this one up

@dhruvkelawala Assigned
