### ISSUE TITLE
test: add test coverage for `RangeCheckBuiltinRunner`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#178]
At the moment, there are quite a few tests missing for the `RangeCheckBuiltinRunner` structure in order to have good coverage. This generates problems in use as is the case here:

https://github.com/keep-starknet-strange/cairo-zig/blob/d043ccf85a54a5d566046fd86d0eafa65f762865/src/vm/builtins/builtin_runner/range_check.zig#L239

The test coverage needs to be improved for the whole structure.

**Comment by oxlime** [comment]
i can take this one

**Comment by tcoratger** [comment]
> i can take this one

@oxlime Assigned
