### ISSUE TITLE
refactor: `MaybeRelocatable` methods to be encapsulated within structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#192]
## Description:
The methods responsible for creating `MaybeRelocatable` instances (`newFromRelocatable`, `fromFelt`, `fromU256`, `fromU64`, `fromSegment`) currently reside outside the `MaybeRelocatable` structure. 

https://github.com/keep-starknet-strange/cairo-zig/blob/72770711ada3777330b7c73f97de2794a51ae03f/src/vm/memory/relocatable.zig#L567-L611

To streamline the code organization and improve encapsulation, the objective is to migrate these creation methods inside the structure itself. This refactor will ensure better encapsulation and cohesive handling of instance creation within the structure.

## Proposed Changes:
- Move creation methods (`newFromRelocatable`, `fromFelt`, `fromU256`, `fromU64`, `fromSegment`) inside the `MaybeRelocatable` structure.
- Adjust method calls and references throughout the codebase accordingly.

## Benefits:
- Enhanced encapsulation by housing instance creation methods within the `MaybeRelocatable` structure.
- Improved code readability and maintainability by consolidating related functionalities.

## Additional Context:
By relocating these creation methods within the structure, we aim to align with best practices in structuring code and ensure a more coherent organization of functionalities within the `MaybeRelocatable` context.

This migration will facilitate a cleaner and more maintainable codebase by centralizing the creation logic of `MaybeRelocatable` instances.

**Comment by dhruvkelawala** [comment]
Please assign this one to me

**Comment by tcoratger** [comment]
> Please assign this one to me

Assigned
