### ISSUE TITLE
feat : add `getPublicMemoryAddresses` method in `MemorySegmentManager` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#199]
## Description

In the `MemorySegmentManager` structure within our Ziglang implementation, we want to introduce a `getPublicMemoryAddresses` method. This method will furnish a list of memory cell addresses, specifically highlighting those that constitute the public memory.

The objective is to facilitate seamless access to the addresses of memory cells forming the public memory within the `MemorySegmentManager` structure.

## Reference for implementation

The proposed method will operate akin to its counterparts in Rust and Python, aiming to deliver an array of addresses representing the public memory cells. Here are references to existing implementations in Rust and Python for guidance and inspiration:

- Reference to the Rust implementation: https://github.com/lambdaclass/cairo-vm/blob/7c1cfd907cf955aff79a6e9dc9d8441008e63995/vm/src/vm/vm_memory/memory_segments.rs#L218-L237
- Reference to the Python implementation: https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_segments.py#L113-L124

## Reference for unit tests

Reference for a unit test in Python: https://github.com/starkware-libs/cairo-lang/blob/10d257de5f49543757599cad9afaa5b4dd6d752b/src/starkware/cairo/lang/vm/memory_segments_test.py#L44-L56

**Comment by dhruvkelawala** [comment]
Please assign this to me

**Comment by tcoratger** [comment]
> Please assign this to me

Assigned
