### ISSUE TITLE
feat: eliminate Rust spies (fn default for Structs)

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#63]
### Description
We clearly have a Rust spy somewhere in the Zig group! Oh no! Please re-factor the code to be Ziggidiomatic :) 

```
/// Represents the operands for an instruction.
const OperandsResult = struct {
    dst: relocatable.MaybeRelocatable,
    res: ?relocatable.MaybeRelocatable,
    op_0: relocatable.MaybeRelocatable,
    op_1: relocatable.MaybeRelocatable,
    dst_addr: relocatable.MaybeRelocatable,
    op_0_addr: relocatable.MaybeRelocatable,
    op_1_addr: relocatable.MaybeRelocatable,

    /// Returns a default instance of the OperandsResult struct.
    pub fn default() OperandsResult {
        return .{
            .dst = relocatable.fromU64(0),
            .res = relocatable.fromU64(0),
            .op_0 = relocatable.fromU64(0),
            .op_1 = relocatable.fromU64(0),
            .dst_addr = relocatable.fromU64(0),
            .op_0_addr = relocatable.fromU64(0),
            .op_1_addr = relocatable.fromU64(0),
        };
    }
};
```

Original code [here](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L401) 

Follow the same idea as in this [PR](https://github.com/keep-starknet-strange/cairo-zig/pull/58/files)

**Comment by tcoratger** [comment]
I think we can close this and #65 and leave things as they are now because `MaybeRelocatable` is of type `union`. The goal here for me is well fulfilled with an initiation at 0, which gives a field with 4 elements at 0.
