### ISSUE TITLE
Add `segments` function as a test util function

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/cairo-zig#75]
To improve and facilitate test coverage (e.g. for the following case which is currently under development: https://github.com/keep-starknet-strange/cairo-zig/issues/8), we need to start developing some useful tests for the core of the VM, the `segments` logic is one of them:
- Details of similar implementation in Rust can be found here: https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/utils.rs#L102-L117
- This can be done after #74 is resolved.

**Comment by oxlime** [comment]
can take have it done :)

**Comment by tcoratger** [comment]
> can take have it done :)

@oxlime Assigned
