### ISSUE TITLE
feat: implement deduceMemoryCell 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#8]
### Description
This is currently blocked because the builtins are not implemented. Once they are, this function should use the builtins memory such as in [this builtin](https://github.com/lambdaclass/cairo-vm/blob/01a5773d4198d083ea645dea5c00133c36ff8321/vm/src/vm/runners/builtin_runner/bitwise.rs#L66)  

### Acceptance criteria
The deduce memory cell function needs to iterate over the vector of builtin runners. Add the necessary field to the VM struct, similar to [here](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_core.rs#L78) and iterate over it similar to [here](https://github.com/lambdaclass/cairo-vm/blob/e6171d66a64146acc16d5512766ae91ae044f297/vm/src/vm/vm_core.rs#L281).

**Comment by tcoratger** [comment]
Please assign me :) Will give it a try
