### ISSUE TITLE
feat: implement keccak builtin 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#80]
### Description 

Builtins constrain certain memory cells in the area of memory shared between the CPU and the builtins.
For inspiration see [Rust](https://github.com/lambdaclass/cairo-vm/blob/01a5773d4198d083ea645dea5c00133c36ff8321/vm/src/vm/runners/builtin_runner/keccak.rs) and [python](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/lang/builtins/keccak/keccak_builtin_runner.py) implementations.

**Comment by tcoratger** [comment]
Will work on that!
