### ISSUE TITLE
feat: add optional trace to CairoVM struct and add enable trace flag

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#9]
Right now the CairoVM is [missing an optional trace field](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L14), which when we are in `enable-trace` mode should be updated with every step of the virtual machine. The trace is a vector of `TraceEntry` of the registers `pc`, `ap`, and `fp`. In `runInstruction` `[function](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L104)` we need to push a new `TraceEntry` struct that receives the registers from `RunContext` [register holder](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/run_context.zig#L12). 

It's OK to push a default value of `RunContext` for the moment but when [this](https://github.com/keep-starknet-strange/cairo-zig/issues/10) is complete the actual value needs to be pushed. 

Add the `enable-trace` flag in [cmd](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/cmd/cmd.zig).

**Comment by lambda-0x** [comment]
i am new to zig and also cairo-vm in general so would be nice if there is any reference to see for example in `cairo-go` or `cairo-vm`.

> In runInstruction [function](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L104) we need to push a new TraceEntry 

where do we need to push this value? should a new field be added in `CairoVM` that has a `Vec<TraceEntry>`?

**Comment by abdelhamidbakhta** [comment]
> i am new to zig and also cairo-vm in general so would be nice if there is any reference to see for example in `cairo-go` or `cairo-vm`.
> 
> > In runInstruction [function](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/core.zig#L104) we need to push a new TraceEntry
> 
> where do we need to push this value? should a new field be added in `CairoVM` that has a `Vec<TraceEntry>`?

yep something like this would work. Assigned to you.

@lana-shanghai the `run_context` of the VM field can be used instead of a default value, so that it will work out of the box when the registers value are actually updated.
